### ISSUE TITLE
putListingsItem API submissions return numerous 100720 (Invalid language data) errors

### ISSUE THREAD

**Issue by lai3221** [amzn/selling-partner-api-models#5010]
I submitted a listing using **putListingsItem**. The request and response are as follows. Why do I see a large number of **100720** error codes?

**Request**
```json
{
  "sellerId": "A3IKLDKKJYSH49",
  "sku": "sel998ialce",
  "marketplaceIds": [
    "A13V1IB3VIYZZH"
  ],
  "productType": "ELECTRONIC_CABLE",
  "attributes": {
    "brand": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "language_tag": "fr_FR",
        "value": "Surgur"
      }
    ],
    "item_name": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "language_tag": "fr_FR",
        "value": "Surgur 3,0M Câble Micro USB Compatible avec Sony Manette PS4"
      }
    ],
    "manufacturer": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "language_tag": "fr_FR",
        "value": "Surgur"
      }
    ],
    "part_number": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "value": "S804"
      }
    ],
    "recommended_browse_nodes": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "value": "14071961031"
      }
    ],
    "country_of_origin": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "value": "CN"
      }
    ],
    "list_price": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "value": "12.99",
        "value_with_tax": "12.99"
      }
    ],
    "gdpr_risk": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "value": "no_electronic_information_stored"
      }
    ],
    "fulfillment_availability": [
      {
        "fulfillment_channel_code": "AMAZON_EU"
      }
    ],
    "product_description": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "language_tag": "fr_FR",
        "value": "Compatible avec Sony PS4, Playstation 4, PS4 Slim, PS4 Pro, Xbox One \/ One S \/ Elite \/ One X"
      }
    ],
    "bullet_point": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "language_tag": "fr_FR",
        "value": "Propre et sans odeur, même avec un snack à la main"
      },
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "language_tag": "fr_FR",
        "value": "Zéro interruption, toujours prêt à jouer —— Jouez tout en rechargeant sans aucune gêne."
      },
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "language_tag": "fr_FR",
        "value": "Compatible avec Sony PS4, Playstation 4, PS4 Slim, PS4 Pro, Xbox One \/ One S \/ Elite \/ One X"
      },
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "language_tag": "fr_FR",
        "value": "Service après-vente: Ce produit peut le remplacement et le retour dans les 30 jours"
      },
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "language_tag": "fr_FR",
        "value": "Contenu de l'emballage: 3,0M Micro USB Câble"
      }
    ],
    "compatible_devices": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "language_tag": "fr_FR",
        "value": "Sony Manette PS4"
      },
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "language_tag": "fr_FR",
        "value": "Xbox One \/ One S \/ Elite \/ One X"
      }
    ],
    "item_package_weight": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "unit": "kilograms",
        "value": "0.06"
      }
    ],
    "item_package_dimensions": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "height": {
          "value": "1.56",
          "unit": "centimeters"
        },
        "length": {
          "value": "19.2",
          "unit": "centimeters"
        },
        "width": {
          "value": "11.52",
          "unit": "centimeters"
        }
      }
    ],
    "condition_type": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "value": "new_new"
      }
    ],
    "batteries_required": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "value": "false"
      }
    ],
    "batteries_included": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "value": "false"
      }
    ],
    "supplier_declared_dg_hz_regulation": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "value": "not_applicable"
      }
    ],
    "number_of_items": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "value": 1
      }
    ],
    "color": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "language_tag": "fr_FR",
        "value": "noir"
      }
    ],
    "connector_type": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "language_tag": "fr_FR",
        "value": "3M Cable Manette PS4"
      }
    ],
    "compatible_phone_models": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "language_tag": "fr_FR",
        "value": "Null"
      }
    ],
    "special_feature": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "language_tag": "fr_FR",
        "value": "Multi-device compatibility"
      }
    ],
    "connector_gender": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "language_tag": "fr_FR",
        "value": "Mâle à Femelle"
      }
    ],
    "unit_count": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "type": {
          "language_tag": "fr_FR",
          "value": "unité"
        },
        "value": 1
      }
    ],
    "size": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "language_tag": "fr_FR",
        "value": "19.2 x 11.52 x 1.56 centimeters"
      }
    ],
    "included_components": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "language_tag": "fr_FR",
        "value": "No"
      }
    ],
    "merchant_suggested_asin": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "value": "B0DKUSYHF"
      }
    ],
    "voltage": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "value": 240,
        "unit": "volts"
      }
    ],
    "accepted_voltage_frequency": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "value": "100v_240v_50hz_60hz"
      }
    ],
    "cable": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "length": [
          {
            "unit": "meters",
            "decimal_value": "3",
            "string_value": "3"
          }
        ],
        "type": [
          {
            "value": "Micro USB",
            "language_tag": "fr_FR"
          }
        ]
      }
    ],
    "supplier_declared_has_product_identifier_exemption": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "value": true
      }
    ],
    "power_plug_type": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "value": "no_plug"
      }
    ],
    "purchasable_offer": [
      {
        "marketplace_id": "A13V1IB3VIYZZH",
        "currency": "EUR",
        "audience": "ALL",
        "our_price": [
          {
            "schedule": [
              {
                "value_with_tax": "12.99"
              }
            ]
          }
        ]
      }
    ]
  }
}
```

**Response**

```json
{
  "sku": "sel998ialce",
  "status": "INVALID",
  "submissionId": "00000000000000000000000000000000000",
  "issues": [
    {
      "code": "100720",
      "message": "Invalid language data provided for in marketplace 4 for attributes Color",
      "severity": "ERROR",
      "attributeNames": [
        "color"
      ],
      "categories": [
        "INVALID_ATTRIBUTE"
      ]
    },
    {
      "code": "100720",
      "message": "Invalid language data provided for in marketplace 4 for attributes Special Features",
      "severity": "ERROR",
      "attributeNames": [
        "special_feature"
      ],
      "categories": [
        "INVALID_ATTRIBUTE"
      ]
    },
    {
      "code": "100720",
      "message": "Invalid language data provided for in marketplace 4 for attributes Model Name",
      "severity": "ERROR",
      "attributeNames": [
        "model_name"
      ],
      "categories": [
        "INVALID_ATTRIBUTE"
      ]
    },
    {
      "code": "100720",
      "message": "Invalid language data provided for in marketplace 4 for attributes Brand Name",
      "severity": "ERROR",
      "attributeNames": [
        "brand"
      ],
      "categories": [
        "INVALID_ATTRIBUTE"
      ]
    },
    {
      "code": "100720",
      "message": "Invalid language data provided for in marketplace 4 for attributes Size",
      "severity": "ERROR",
      "attributeNames": [
        "size"
      ],
      "categories": [
        "INVALID_ATTRIBUTE"
      ]
    },
    {
      "code": "100720",
      "message": "Invalid language data provided for in marketplace 4 for attributes Product Description",
      "severity": "ERROR",
      "attributeNames": [
        "product_description"
      ],
      "categories": [
        "INVALID_ATTRIBUTE"
      ]
    },
    {
      "code": "1CSS0720",
      "message": "Invalid language data provided for in marketplace 4 for attributes Title",
      "severity": "ERROR",
      "attributeNames": [
        "item_name"
      ],
      "categories": [
        "INVALID_ATTRIBUTE"
      ]
    },
    {
      "code": "100720",
      "message": "Invalid language data provided for in marketplace 4 for attributes Compatible Phone Models",
      "severity": "ERROR",
      "attributeNames": [
        "compatible_phone_models"
      ],
      "categories": [
        "INVALID_ATTRIBUTE"
      ]
    },
    {
      "code": "100720",
      "message": "Invalid language data provided for in marketplace 4 for attributes Connector Gender",
      "severity": "ERROR",
      "attributeNames": [
        "connector_gender"
      ],
      "categories": [
        "INVALID_ATTRIBUTE"
      ]
    },
    {
      "code": "100720",
      "message": "Invalid language data provided for in marketplace 4 for attributes Included Components",
      "severity": "ERROR",
      "attributeNames": [
        "included_components"
      ],
      "categories": [
        "INVALID_ATTRIBUTE"
      ]
    },
    {
      "code": "100720",
      "message": "Invalid language data provided for in marketplace 4 for attributes Bullet Point",
      "severity": "ERROR",
      "attributeNames": [
        "bullet_point"
      ],
      "categories": [
        "INVALID_ATTRIBUTE"
      ]
    },
    {
      "code": "100720",
      "message": "Invalid language data provided for in marketplace 4 for attributes Manufacturer",
      "severity": "ERROR",
      "attributeNames": [
        "manufacturer"
      ],
      "categories": [
        "INVALID_ATTRIBUTE"
      ]
    },
    {
      "code": "100720",
      "message": "Invalid language data provided for in marketplace 4 for attributes Connector Type",
      "severity": "ERROR",
      "attributeNames": [
        "connector_type"
      ],
      "categories": [
        "INVALID_ATTRIBUTE"
      ]
    },
    {
      "code": "100720",
      "message": "Invalid language data provided for in marketplace 4 for attributes Style",
      "severity": "ERROR",
      "attributeNames": [
        "style"
      ],
      "categories": [
        "INVALID_ATTRIBUTE"
      ]
    },
    {
      "code": "100720",
      "message": "Invalid language data provided for in marketplace 4 for attributes [\"type\"]",
      "severity": "ERROR",
      "categories": [
        "INVALID_ATTRIBUTE"
      ]
    },
    {
      "code": "100720",
      "message": "Invalid language data provided for in marketplace 4 for attributes Compatible Devices",
      "severity": "ERROR",
      "attributeNames": [
        "compatible_devices"
      ],
      "categories": [
        "INVALID_ATTRIBUTE"
      ]
    }
  ]
}
```

**Comment by weilinggu** [comment]
Hi @lai3221 

The error message seems to be pointing at a marketplace that is not consistent with the marketplace you have in your submission. Can you [open a support case](https://developer.amazonservices.com/support) with your submission to investigate?

Thanks
Weiling
Amazon Selling Partner Services

**Comment by lai3221** [comment]
Hi @weilinggu 

In my request body, I made some modifications to the sellerId, sku, brand, merchant_suggested_asin, and manufacturer attributes; all other data was officially submitted.

I have already published the product information in France.

Some of the error messages are a bit puzzling, such as the brand attribute. Its value is just my brand name, and the listings also use the same word, yet it published successfully.

I've debugged it several times, but I can't find any information about this type of error online. Could you please help me identify the possible problem?

Thanks

**Comment by weilinggu** [comment]
Hi @lai3221 

This is indeed a puzzling case because the error is showing a marketplace not consistent with the marketplace in your submission. However, we will need more information to help troubleshoot. I recommend [open a support case](https://developer.amazonservices.com/support) with your submission IDs to investigate.

What was the error on your brand name? Is it language related as well?

Thanks
Weiling 
Amazon Selling Partner Services

**Comment by ajalexsmith** [comment]
I'm getting exactly the same issue with Book Data. Complaining with a 100720, have raised a case 3 months ago and get a nice auto reply every couple of days with no resolution, so would be good to see if you get a resolution! The same code works on some products but not others. Amazon put a 'fix' in place but it just fixed the one I gave as an example but everything else is still broken.

Issues found: 100720 - Invalid language data provided for in marketplace 7 for attributes Subject (Severity: ERROR)

**Comment by ikepaul** [comment]
Did anyone get a solution to this?
