### ISSUE TITLE
Validation issue while posting inboundplan - Fulfillment Inbound API v2024-03-20

### ISSUE THREAD

**Issue by shantikolli** [amzn/selling-partner-api-models#650]
Hi

As per the documentation, there is no phone Number required for source address during inbound plan. I posed without phoneNumber and it throws validation as 

{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "1 validation error detected: Value null at 'request.sourceAddress.phoneNumber' failed to satisfy constraint: Member must not be null",
            "details": ""
        }
    ]
}

I thought may be the documentation missed this information so I tried to include the phone number and post the request. Again it throws the same validation 

attaching the screenshots
![withoutPhone](https://github.com/amzn/selling-partner-api-models/assets/170322609/c4f3c836-a583-4ffd-b02a-9f67052dc33f)
![withphone](https://github.com/amzn/selling-partner-api-models/assets/170322609/f973a86a-900d-4c62-a730-b63049fa1c44)

**Comment by KirillChekalin** [comment]
i'm having the same issue.

**Comment by garply1** [comment]
Same here. The fulfillment Inbound isn't even close to being ready. I can't believe it was even released as "early/preview".

**Comment by ssamran15** [comment]
I am having the same issue, no matter what you do you'll receive this same error. furthermore, I am also getting 500 internal server error in getShipment and item/quantity issue in setPackingInformation. so yeah it seems like the API is still under development.

**Comment by KirillChekalin** [comment]
📢 Update: createInboundPlan API Now Working Without Phone Number
Hi everyone!

I wanted to share an update for those of us using the createInboundPlan API. 🎉

What happened?
Previously, many of us encountered an error when creating an inbound plan, which indicated that the phoneNumber field in the sourceAddress was mandatory. This was unexpected since the documentation did not list this field as required.

Good news!
Today, I discovered that this issue has been resolved. The phone number is no longer required in the request to create an inbound plan, and the API now works as documented.

**Comment by shantikolli** [comment]
@KirillChekalin Thank you for the update. Yes, I see that it works now. Its quite surprising that the documentation is not consistent. If the issue is fixed, they should at least update. I created a case yesterday and I didnt receive any update from Amazon support team.

**Comment by or-en** [comment]
This issue has returned

[400] 1 validation error detected: Value null at 'request.sourceAddress.phoneNumber' failed to satisfy constraint: Member must not be null (InvalidInput)

Anyone had it as well?

**Comment by shantikolli** [comment]
@or-en Looks like then it is working intermittently, strange!!

**Comment by garply1** [comment]
The bug is back. At least this time you can add phoneNumber to your schema and it will work. Last time if failed no matter whether is was included or not.

**Comment by ElvinsSun** [comment]
I have add phoneNumber to sourceAddress.But it's also get errors.The bug is back

**Comment by shreeharsh-a** [comment]
@puppsupr

**Comment by puppsupr** [comment]
Hi,
We have a [new release](https://developer-docs.amazon.com/sp-api/changelog/new-fulfillment-inbound-api-v2024-03-20-june-release) and change in the [model](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-model) for additional functionalities. Please try to import the new model and retry which should resolve the issues.
